import { Config } from './config.js';

export class APIClient {
    static async sendJob(payload) {
        const info = await Config.getAppInfo();
        if (!info.url) throw new Error("Aplikasi OmniFetch belum diatur.");
        
        const origin = new URL(info.url).origin;
        if (!origin.startsWith("http")) throw new Error("URL tidak valid.");
        
        try {
            const res = await fetch(`${origin}/api/start`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                    'X-App-Session': info.token || ''
                },
                body: JSON.stringify(payload)
            });
            
            if (!res.ok) {
                let errText = "Gagal mengirim tugas.";
                try {
                    const errJson = await res.json();
                    errText = errJson.error || errText;
                } catch (e) {}
                throw new Error(errText);
            }
            return await res.json();
        } catch (e) {
            throw new Error(`Koneksi error: ${e.message}`);
        }
    }

    static async syncCookies(domains) {
        const info = await Config.getAppInfo();
        if (!info.url || !info.cookieSync) return;
        
        const origin = new URL(info.url).origin;
        if (origin.startsWith('http://') && !origin.includes('localhost') && !origin.includes('127.0.0.1')) {
            console.warn("Cookie sync diblokir untuk HTTP non-lokal demi keamanan.");
            return;
        }

        let allCookies = [];
        for (const d of domains) {
            try {
                const cookies = await chrome.cookies.getAll({ domain: d });
                allCookies = allCookies.concat(cookies);
            } catch (e) {}
        }
        
        if (allCookies.length === 0) return;
        
        let netscape = "# Netscape HTTP Cookie File\\n# Generated by OmniFetch Companion\\n";
        const seen = new Set();
        for (const c of allCookies) {
            const key = `${c.domain}|${c.name}|${c.path}`;
            if (seen.has(key)) continue;
            seen.add(key);
            netscape += `${c.domain}\\t${c.domain.startsWith('.') ? 'TRUE' : 'FALSE'}\\t${c.path}\\t${c.secure ? 'TRUE' : 'FALSE'}\\t${c.expirationDate ? Math.floor(c.expirationDate) : 0}\\t${c.name}\\t${c.value}\\n`;
        }
        
        try {
            await fetch(`${origin}/upload-cookies`, {
                method: 'POST',
                headers: {
                    'Content-Type': 'text/plain',
                    'X-App-Session': info.token || ''
                },
                body: netscape
            });
        } catch (e) {}
    }
}
