// Only observe responses. Do not block ads, change requests, or read cookies.
function classify(url, mime) {
  const path = new URL(url).pathname.toLowerCase();
  if (/\.(vtt|srt)$/.test(path) || mime.includes('text/vtt')) return 'subtitle';
  if (/\/config-[^/]+\.json$/.test(path)) return 'config';
  if (/\.(m3u8|mpd)$/.test(path) || /mpegurl|dash\+xml/.test(mime)) return 'playlist';
  if (/\.(mp4|webm)$/.test(path) || /video\/(mp4|webm)/.test(mime)) return 'video';
  return null;
}

let queue = Promise.resolve();
function enqueue(fn) { queue = queue.then(fn).catch(() => {}); }

// === Smart Sniffer: detect hidden videos on any site ===
const SNIFFER_IGNORE = ['youtube.com','instagram.com','tiktok.com','twitter.com','x.com','facebook.com','idlixku.com','majorplay.net'];
const snifferCounts = {};
chrome.webRequest.onResponseStarted.addListener(d => {
  if (d.tabId < 0 || ![200,206].includes(d.statusCode)) return;
  const urlHost = new URL(d.url).hostname;
  if (SNIFFER_IGNORE.some(h => urlHost.endsWith(h))) return;
  const mime = (d.responseHeaders || []).find(h => h.name.toLowerCase() === 'content-type')?.value || '';
  const isMedia = /video\/(mp4|webm)|application\/(x-mpegurl|vnd.apple.mpegurl|dash\+xml)/.test(mime) || /\.(m3u8|mpd|mp4)$/.test(new URL(d.url).pathname);
  if (!isMedia) return;
  enqueue(async () => {
    if (!snifferCounts[d.tabId]) snifferCounts[d.tabId] = { count: 0, firstUrl: d.url };
    snifferCounts[d.tabId].count++;
    if (snifferCounts[d.tabId].count === 1) {
      try { await chrome.tabs.sendMessage(d.tabId, { type: 'omni-sniffer', count: 1, url: d.url }); } catch(e) {}
    }
  });
}, { urls: ['*://*/*'] }, ['responseHeaders']);

// === Main frame: clear state + sniffer ===
chrome.webRequest.onBeforeRequest.addListener(d => {
  if (d.tabId < 0 || d.type !== 'main_frame') return;
  enqueue(async () => {
    delete snifferCounts[d.tabId];
    await chrome.storage.session.remove('tab:'+d.tabId);
    await chrome.action.setBadgeText({tabId:d.tabId,text:''});
  });
}, {urls:['http://*/*','https://*/*'],types:['main_frame']});

// === HLS/playlist sniffer for streaming sites ===
const streamFilter = {urls:['https://*.idlixku.com/*','https://*.majorplay.net/*']};
chrome.webRequest.onResponseStarted.addListener(d => {
  if (d.tabId < 0 || ![200,206].includes(d.statusCode)) return;
  const mime = (d.responseHeaders || []).find(h=>h.name.toLowerCase()==='content-type')?.value || '';
  const kind = classify(d.url,mime.toLowerCase());
  if (!kind) return;
  enqueue(async () => {
    const key='tab:'+d.tabId;
    const stored=(await chrome.storage.session.get(key))[key] || [];
    const items=stored.filter(x=>x.url!==d.url && Date.now()-x.time<3600000);
    items.push({url:d.url,kind,time:Date.now(),referer:d.initiator||''});
    await chrome.storage.session.set({[key]:items.slice(-60)});
    await chrome.action.setBadgeBackgroundColor({color:'#e7193f',tabId:d.tabId});
    await chrome.action.setBadgeText({text:String(Math.min(items.length,60)),tabId:d.tabId});
  });
}, streamFilter, ['responseHeaders']);

chrome.tabs.onRemoved.addListener(id => enqueue(() => {
  delete snifferCounts[id];
  chrome.storage.session.remove('tab:'+id);
}));

// === Context Menu: Right-click anywhere ===
chrome.runtime.onInstalled.addListener(() => {
  chrome.contextMenus.create({
    id: 'omni-download-link',
    title: '\uD83D\uDE80 OmniFetch: Sedot ke VPS',
    contexts: ['link', 'video', 'image', 'page']
  });
  chrome.contextMenus.create({
    id: 'omni-download-selection',
    title: '\uD83D\uDE80 OmniFetch: Unduh URL Ini',
    contexts: ['selection']
  });
});

chrome.contextMenus.onClicked.addListener(async (info, tab) => {
  const settings = await chrome.storage.local.get(['app','token']);
  if (!settings.app) { chrome.runtime.openOptionsPage(); return; }
  const appOrigin = new URL(settings.app).origin;
  const url = info.linkUrl || info.srcUrl || info.selectionText || info.pageUrl;
  if (!url) return;
  await chrome.tabs.create({
    url: appOrigin + '/#import=' + encodeURIComponent(JSON.stringify({ urls: url, mode: 'ytdlp', media_type: 'video' }))
  });
});

// === Auto Cookie Sync (silent, every 60 min) ===
async function silentCookieSync() {
  const settings = await chrome.storage.local.get(['app','token','auto_cookie_sync']);
  if (!settings.app || !settings.auto_cookie_sync) return;
  const domains = ['.instagram.com','instagram.com','.youtube.com','youtube.com','.tiktok.com','tiktok.com'];
  let allCookies = [];
  for (const d of domains) {
    try { allCookies = allCookies.concat(await chrome.cookies.getAll({ domain: d })); } catch(e) {}
  }
  if (allCookies.length === 0) return;
  let netscape = "# Netscape HTTP Cookie File\n# Generated by OmniFetch Companion\n";
  const seen = new Set();
  for (const c of allCookies) {
    const key = `${c.domain}|${c.name}|${c.path}`;
    if (seen.has(key)) continue; seen.add(key);
    netscape += `${c.domain}\t${c.domain.startsWith('.')?'TRUE':'FALSE'}\t${c.path}\t${c.secure?'TRUE':'FALSE'}\t${c.expirationDate?Math.floor(c.expirationDate):0}\t${c.name}\t${c.value}\n`;
  }
  try {
    await fetch(new URL(settings.app).origin + '/upload-cookies', {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain', 'X-App-Token': settings.token || '' },
      body: netscape
    });
  } catch(e) {}
}

// Alarm for periodic sync
chrome.alarms.create('omni-cookie-sync', { periodInMinutes: 60 });
chrome.alarms.onAlarm.addListener(alarm => {
  if (alarm.name === 'omni-cookie-sync') silentCookieSync();
});

// === Original panel message handler (idlixku) ===
chrome.runtime.onMessage.addListener((message,sender,reply)=>{
  if(sender.id!==chrome.runtime.id||!sender.tab||sender.frameId!==0)return;
  let host;try{host=new URL(sender.url).hostname;}catch{return;}
  if(!(host==='idlixku.com'||host.endsWith('.idlixku.com')))return;
  if(!['panel-status','panel-download','panel-settings','panel-copy'].includes(message.type))return;
  (async()=>{
    await queue;
    const list=((await chrome.storage.session.get('tab:'+sender.tab.id))['tab:'+sender.tab.id]||[]).filter(x=>Date.now()-x.time<3600000);
    const media=list.filter(x=>x.kind==='config').sort((a,b)=>b.time-a.time)[0];
    const settings=await chrome.storage.local.get('app');
    if(message.type==='panel-status')return {found:!!media,configured:!!settings.app};
    if(message.type==='panel-settings'){await chrome.runtime.openOptionsPage();return {ok:true};}
    if(message.type==='panel-copy'){if(!media)throw Error('Playlist belum ditemukan.');return {url:media.url};}
    if(!media)throw Error('Playlist belum ditemukan. Putar film terlebih dahulu.');
    if(!settings.app)throw Error('Isi alamat aplikasi terlebih dahulu.');
    const base=new URL(settings.app);
    if(!['http:','https:'].includes(base.protocol)||!base.hostname)throw Error('Alamat aplikasi tidak valid.');
    const group=new URL(media.url).pathname.match(/^\/v\/[^/]+\/[^/]+\//)?.[0];
    const subs=list.filter(x=>x.kind==='subtitle'&&group&&new URL(x.url).pathname.startsWith(group)).sort((a,b)=>Number(/\/i18n\/id\//.test(b.url))-Number(/\/i18n\/id\//.test(a.url))||b.time-a.time);
    const payload={url:media.url,mode:'direct',name:(sender.tab.title||'Video').replace(/\s*[|/]\s*[^|/]+$/i,'').slice(0,100),referer:sender.tab.url,subtitle_url:subs[0]?.url||''};
    await chrome.tabs.create({url:base.origin+'/#import='+encodeURIComponent(JSON.stringify(payload))});
    return {ok:true};
  })().then(reply).catch(e=>reply({error:e.message}));
  return true;
});
